### ISSUE TITLE
Probably my fault 

### ISSUE THREAD

**Issue by manbearpig26** [poseidon-code/youtube-viewbot#1]
I'm new to this but I'm learning along the way, When I run the program it brings up the windows of chrome but non of them connect to said video. Is that to do with the proxies i chose? Does sock4/sock5 proxies make a difference?

**Comment by poseidon-code** [comment]
yes most probably, google won't allow any other other proxies besides https
& http,
try to use https 🙂

**Comment by manbearpig26** [comment]
Thank you so much. Your work is the first I've taken time to try out : )

**Comment by poseidon-code** [comment]
Awesome, thanks!
