### ISSUE TITLE
waiting and waiting for nothing

### ISSUE THREAD

**Issue by medicenplex** [poseidon-code/youtube-viewbot#10]
Is working?
because i was waiting with my 1k proxies that i already paid and i have the same views in youtube 

![imagen](https://github.com/poseidon-code/youtube-viewbot/assets/140880739/944d5a3b-0835-4769-994c-36e3243464f7)

**Comment by poseidon-code** [comment]
The `proxy-list.txt` file contains IP addresses and their respective host ports in the following pattern : `<IP address>:<port>` per line.

Make sure if you have the proxies arranged & structured like this inside `proxy-list.txt`.

```txt
134.87.56.146:3677
213.89.37.145:3523
145.123.77.143:987
```
Also, all proxies may not work, as they may be blocked by Google themselves.
