### ISSUE TITLE
proxy.py doesn't retrieve any proxies

### ISSUE THREAD

**Issue by Vilagamer999** [poseidon-code/youtube-viewbot#2]
![image](https://user-images.githubusercontent.com/30276916/112067267-10399180-8b68-11eb-9059-64d457aceb27.png)
My wifi is working fine, I've tried proxies from other websites but they don't seem to work (brings up blank "data:," site)
I have allowed it to connect to the internet and I also made sure to whitelist it on my antiviruses and firewall

**Comment by poseidon-code** [comment]
Ok, I have checked the program, it is working fine, so here are some variables that may be causing you some problems : 
1. make sure to have Chrome browser installed in your system (the program is currently specifically written for Chrome browser only)
2. make sure to download the chromedriver.exe (included in this repo) specifically for your Chrome browser version. Check your Chrome browser version and get yours chromedriver.exe from here - https://chromedriver.chromium.org/downloads

hope this helps 😃
