### ISSUE TITLE
proxy list empty

### ISSUE THREAD

**Issue by boogieiskool** [poseidon-code/youtube-viewbot#5]
I have followed the instructions and have done so with no errors, but when I run the command with the url in it. it says "proxies found : 0" and when I look in the proxy-list, there is nothing in it, how can I fix this?

**Comment by poseidon-code** [comment]
Proxies were scrapped from the web, where if the layout of the website changes there is always a chance of not getting any proxies. Thanks for submitting an issue, I definitely will look into it.

**Comment by poseidon-code** [comment]
Hey @boogieiskool , I have checked the code, it is working just fine, although here are some things that you can do to fix your problem :
1. Make sure you have installed Google Chrome (or Chromium) in your Computer.
2. Make sure you have downloaded the same chrome driver version as that of your Google Chrome version. For Google Chrome or Chromium version 102.0.5005.61 (i.e. latest version) use this [chromedriver](https://chromedriver.storage.googleapis.com/index.html?path=102.0.5005.61/)
3. Make sure after downloading this driver, you copy that to the `youtube-viewbot` folder.

Currently, the code base was made around 64bit Windows OS systems, I will be working on making it usable for all the systems with support for all other browsers with also automating all the major processes like downloading right webdriver, setting up proxies and finally using viewbot.

**Comment by medicenplex** [comment]
no wrking
