### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by SayaAEP** [poseidon-code/youtube-viewbot#6]
![image](https://user-images.githubusercontent.com/91467886/204308752-34dd1525-98a2-497c-bd40-ca7c4a22337f.png)
chromedriver installed but noting result
i updated the chromedriver.exe to chromedriver(linux) #5 

Ubuntu WSL2
desktop env is Xrdp
google chrome (non chromium) working
![image](https://user-images.githubusercontent.com/91467886/204309302-a43e8f57-3d5f-4133-9b8c-067c352d5c92.png)

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/204310627-4488f335-d381-47a5-a52b-84cc0eaf6508.png)
if i run on real windows os
same result

**Comment by poseidon-code** [comment]
Hello @TukangM, just to start off simply (i.e.: using the script directly on Windows OS & not on WSL),
The proxy script is running perfectly on Windows. 

To clarify on the problem, you might have to check that you have Chrome installed, and the webdriver should be exactly for the same version as that of your browser version.

Typical issues along with important prerequisites on using these scripts are mentioned in #5

**Comment by TukangM** [comment]
Oh ok

**Comment by TukangM** [comment]
I try later. I use Ms edge fir daily browsing
