### ISSUE TITLE
How do you whether its working or not

### ISSUE THREAD

**Issue by lnb2g** [poseidon-code/youtube-viewbot#7]
I have followed the readme and it running but the browswer/driver seems to got kill instantly, is this normal? How do I know whether it was running or not. Thanks

**Comment by poseidon-code** [comment]
The browser can get closed for 2 reasons : sleep duration is low & an exception occurs when opening the driver (browser).

An exception may occur when the driver cannot be opened, or when the proxy IP is blocked, or when the driver & the browser are not of compatible versions, etc.

The browser should get killed instantly when the view duration is very small _(like 1 - 5 seconds)_. The `driver.quit()` only runs after the given time period. You can check out this part of code :
https://github.com/poseidon-code/youtube-viewbot/blob/90dccb2791e8c3b0571b39f41a60ab381afb1a1c/viewbot.py#L27-L33

To test out whether the browser is running, you can just comment out the `browser.quit()` line ([line 33](https://github.com/poseidon-code/youtube-viewbot/blob/90dccb2791e8c3b0571b39f41a60ab381afb1a1c/viewbot.py#L33)) which doesn't closes the browser when after the given sleep duration or when an exception occurs.
