### ISSUE TITLE
Total Proxies 0 ?

### ISSUE THREAD

**Issue by medicenplex** [poseidon-code/youtube-viewbot#9]
Hi,
I did everything and they told me Total Proxies: 0 
¿what i need to do and where?

![imagen](https://github.com/poseidon-code/youtube-viewbot/assets/140880739/1b4be5c5-f453-434a-9a51-15a0f497f62c)

**Comment by medicenplex** [comment]
THey told: Generated "proxy-list.txt" but i can't see it and i can put my proxies :S 

![imagen](https://github.com/poseidon-code/youtube-viewbot/assets/140880739/31db2ddd-7bde-43e4-a16d-c45d565964ec)

**Comment by poseidon-code** [comment]
It seems like the `Free Proxy Lists` [https://www.freeproxylists.net](https://www.freeproxylists.net) website is inaccessible at the moment. As the `proxy.py` script is using that site for getting proxies, hence the script is generating `0` proxies.

I will update the proxy script soon. Meanwhile, one can directly make a `proxy-list.txt` file and add their collected proxies to it in the following structure : `<IP address>:<port>` per line

**example : _`proxy-list.txt`_**
```txt
134.87.56.146:3677
213.89.37.145:3523
145.123.77.143:987
```

**Comment by poseidon-code** [comment]
Fixed in [a7bc153](https://github.com/poseidon-code/youtube-viewbot/commit/a7bc153159719827c949654abd00292f9478c326) commit. New proxy provider added.
